#ifndef GAME_CONSTANTS_H
#define GAME_CONSTANTS_H

#include <SDL2/SDL.h>

#define WIDTH 1920
#define HEIGHT 1080
#define FPS 30

#define BACKGROUND_COLOR 0x444444
#define TILE_UNCLICKED_COLOR 0x000000
#define TILE_UNCLICKED_HIGHLIGHT_COLOR 0x0F0F0F
#define TILE_CLICKED_COLOR 0xAAAAAA
#define TILE_CLICKED_MINE_COLOR 0xFF0000
#define TILE_FLAGGED_COLOR 0x55BBAA
#define TILE_FLAGGED_HIGHLIGHT_COLOR 0x65CBBA
#define TILE_NUM_COLOR 0x00A1BB

#define DEFAULT_ROWS 9
#define DEFAULT_COLS 9
#define DEFAULT_MINES 10
#define PAD_INNER 0
#define PAD_OUTER 30

#endif /* GAME_CONSTANTS_H */
